spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.60.137:3306/tumo_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

  redis:
    port: 6379
    host: 172.16.60.137
