spring:
  # 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://tumo-boot-mysql:3306/tumo_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

  # Redis配置
  redis:
    port: 6379
    host: tumo-boot-redis
