spring:
  # 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://tumo-boot-mysql:3306/tumo_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

  # Redis配置
  redis:
    port: 6379
    host: tumo-boot-redis

# 自定义配置
tumo-boot:
  # Oss配置
  file:
    remote-path: http://127.0.0.1:80/upload
    # 生产环境下，文件上传的地址应该是Web容器映射的可访问的地址，这里设置为nginx默认映射地址
    upload-path: /usr/local/var/www/upload
