version: "3.5"

services:
  tumo-boot-mysql:
    image: mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: tumo-boot-mysql
    ports:
      - 3306:3306

  tumo-boot-redis:
    image: redis
    restart: always
    hostname: tumo-boot-redis
    container_name: tumo-boot-redis
    ports:
      - 8848:8848

  tumo-boot:
    image: ${REGISTER}/tumo/tumo_boot:${TAG}
    restart: always
    container_name: tumo-boot
    hostname: tumo-boot
    environment:
      - TZ=Asia/Shanghai

  tumo-boot-ui:
    image: ${REGISTER}/tumo/tumo_boot_ui:${TAG}
    restart: always
    container_name: tumo-boot-ui
    ports:
      - 8091:80
