server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: Tumo-Boot
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  type-aliases-package: cn.tycoding.boot.modules.**.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

logging:
  level:
    springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator: ERROR

knife4j:
  enable: true

# 系统自定义配置
tumo-boot:
  # 权限配置
  auth:
    skip-url:
      - /blog/article/filter/list
  # 日志配置
  log:
    # 是否开始日志打印
    enable: true
  # Mybatis 配置
  mybatis:
    # 是否开启SQL打印
    enable: true
  # Swagger配置
  swagger:
    title: Tumo Boot 项目API接口文档
    description: 项目开源地址：https://github.com/Tumo-Team/Tumo-Boot
    author: TyCoding
    url: https://tycoding.cn
    email: tycoding@sina.com
    version: v1.0
